apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels: 
    podrace-role: client
spec:
  replicas: 2
  selector:
    matchLabels:
      podrace-role: client
  template:
    metadata:
      labels:
        podrace-role: client
    spec:
      containers:
      - name: wrk
        image: williamyeh/wrk
        command: [ "/bin/sh", "-c", "while true; do sleep 2; done" ]