apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    podrace-role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      podrace-role: server
  template:
    metadata:
      labels:
        podrace-role: server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80