apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    podrace-role: server
spec:
  selector:
    podrace-role: server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443