apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    podrace: "true"
    podrace-role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      podrace: "true"
      podrace-role: server
  template:
    metadata:
      labels:
        podrace: "true"
        podrace-role: server
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80